version: '3.8'

services:
  docker-go-albums:
    depends_on:
      - postgres
    build:
      context: .
    container_name: go-rest-server
    hostname: go-rest-server
    networks:
      - mynet
    ports:
      - 80:8080
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    container_name: albums-pg-2
    image: postgres
    hostname: db
    networks:
      - mynet
    ports:
      - 5432:5432
      - 8080:8080
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwordHere
      POSTGRES_DB: album_db
    volumes:
      - postgres-data-albums:/var/lib/postgresql/data
    restart: unless-stopped
    
volumes:
  postgres-data-albums:

networks:
  mynet:
    driver: bridge
